#!/usr/bin/env bash
# Install a git pre-push hook that runs `make pre-push`.
# This is the local atomic CI gate: same checks as .github/workflows/ci.yml
# but executed on the laptop before the push reaches GitHub.
#
# Idempotent: replaces existing pre-push hook with one managed by this
# script. The hook marker is "Generated by scripts/install-pre-push-hook.sh"
# so re-running just overwrites the same hook.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

if [ ! -f Makefile ]; then
    echo "ERROR: no Makefile in $(pwd); refusing to install pre-push hook" >&2
    exit 1
fi

mkdir -p .git/hooks

HOOK_FILE=".git/hooks/pre-push"

cat > "$HOOK_FILE" <<'HOOK'
#!/usr/bin/env bash
# Generated by scripts/install-pre-push-hook.sh — do not edit by hand.
# Local pre-push gate. Runs the same checks as the GitHub Actions
# workflow on the local laptop. The actual ci.yml runs on GitHub
# Actions regardless of this hook; this is a fast local gate that
# catches breakage before push.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
if [ -f Makefile ]; then
    echo "[pre-push] running local atomic CI gate..."
    make pre-push
fi
HOOK

chmod +x "$HOOK_FILE"

echo "installed $HOOK_FILE — runs 'make pre-push' on every push"
